import { searchMetadata } from './seo.mjs';
const arrow = '<span aria-hidden="true">↗</span>';
const eyebrow = text => `<p class="eyebrow">${text}</p>`;
const button = (text, href, style = '') => `<a class="button ${style}" href="${href}">${text}${arrow}</a>`;
const logo = () => `<img class="brand-logo" src="assets/logo-adobe.png" alt="Via Nova Marketing — A Higher Way Forward" width="1390" height="521">`;
const disciplines = [
  { title: 'Brand strategy', subtitle: 'A clear direction.', body: 'Understand your audience. Define your difference. Build a practical plan that gives your marketing a purpose.', details: ['Audience & market research', 'Brand positioning', 'Marketing planning'] },
  { title: 'Brand identity', subtitle: 'A distinct presence.', body: 'Translate your direction into a visual identity and voice that feel like your business, wherever people meet it.', details: ['Visual identity', 'Brand voice & messaging', 'Creative direction'] },
  { title: 'Web & digital', subtitle: 'A connected experience.', body: 'Create a thoughtful online home for your brand, with clear content and a natural path from interest to action.', details: ['Website strategy & design', 'Content structure', 'Customer journeys'] },
  { title: 'Content & campaigns', subtitle: 'A purposeful next step.', body: 'Bring your story to the right channels with consistent content, considered campaigns, and a plan to learn from the response.', details: ['Social content planning', 'Campaign concepts', 'Measurement planning'] }
];
const serviceCards = () => disciplines.map((s,i)=>`<article class="service-card"><span class="index">0${i+1}</span><h3>${s.title}</h3><p>${s.body}</p><a href="services.html#service-${i+1}" class="small-link">Explore ${s.title.toLowerCase()} ${arrow}</a></article>`).join('');
const cta = () => `<section class="cta"><div class="container cta-inner"><div>${eyebrow('A higher way forward')}<h2>Your next chapter<br>starts with a conversation.</h2></div><div><p>Let’s begin with where you are.<br>And where you want to go.</p>${button('Let’s talk', 'contact.html')}</div></div></section>`;
const workPreview = () => `<div class="portfolio-placeholder"><div class="portfolio-heading"><span class="index">OUR WORK</span><span class="status-label">Portfolio in development</span></div><h3>Every brand has a story.<br>Ours is taking shape.</h3><p>Our case studies will share the challenge, the thinking, and the work behind each project.</p><a class="small-link" href="work.html">View portfolio updates ${arrow}</a></div>`;
export const pages = {
  index: {
    title: 'Marketing Strategy & Brand Design in Toronto',
    description: 'Toronto-based Via Nova Marketing brings together marketing strategy, brand identity, website design, and content planning. A Higher Way Forward.',
    content: `<section class="home-hero"><img class="hero-photo" src="assets/hero-adobe.png" alt="A winding mountain road rising toward a golden sunrise" width="1536" height="1024" fetchpriority="high"><div class="hero-wash"></div><div class="container hero-content">${eyebrow('Strategy meets a brighter tomorrow')}<h1>Higher brands.<br>Brighter<br>tomorrows.</h1><p class="hero-subtitle">Strategic marketing for what’s next.</p><p class="hero-description">Move forward with a clearer vision,<br>a stronger story, and a purposeful plan.</p><div class="hero-actions">${button('A higher way forward', 'contact.html')}<a class="text-link" href="services.html">Discover our services <span aria-hidden="true">↓</span></a></div></div><div class="hero-signature">STRATEGY.<br>CREATIVITY.<br>REAL GROWTH.</div></section><section class="brand-statement"><div class="container statement-grid">${eyebrow('The Via Nova perspective')}<h2>Bolder brands.<br>Brighter tomorrows.</h2><p>Via Nova Marketing helps brands move forward with strategic creativity, clarity, and real growth.</p></div></section><section class="section container"><div class="section-heading"><div>${eyebrow('01 / Our services')}<h2>Strategy gives direction.<br>Creativity brings it to life.</h2></div><p>From the first question to the next touchpoint, bring your marketing together.</p></div><div class="service-grid">${serviceCards()}</div></section><section class="about-panel container"><div class="identity-panel">${logo()}<p>STRATEGIC. MODERN. FORWARD.<br>TRUSTWORTHY. HUMAN.</p></div><div class="about-copy">${eyebrow('02 / Our approach')}<h2>A higher perspective.<br>A more thoughtful path.</h2><p>Good marketing begins with understanding: the business, the people it serves, and the change it wants to make.</p><p>We connect that understanding to a clear story and a consistent experience. Purpose in the thinking. Care in the details.</p>${button('Meet Via Nova', 'about.html', 'outline')}</div></section><section class="section container"><div class="section-heading"><div>${eyebrow('03 / Our work')}<h2>Thoughtful work.<br>Meaningful stories.</h2></div><p>A space for the brands, ideas, and experiences we help shape.</p></div>${workPreview()}</section>${cta()}`
  },
  services: {
    title: 'Brand Strategy, Web Design & Marketing Services', description: 'Brand strategy, identity, digital experiences, and content. Discover the Via Nova Marketing approach.',
    content: `<section class="page-intro container">${eyebrow('Our services')}<h1>One clear vision.<br>A connected way forward.</h1><p>Strategy. Creativity. Real growth.</p></section><section class="service-details container">${disciplines.map((s,i)=>`<article class="service-detail" id="service-${i+1}"><span class="index">0${i+1}</span><div><p class="eyebrow">${s.title}</p><h2>${s.subtitle}</h2></div><div><p>${s.body}</p><ul>${s.details.map(d=>`<li>${d}</li>`).join('')}</ul><a class="small-link" href="contact.html">Let’s talk about your project ${arrow}</a></div></article>`).join('')}</section><section class="process section"><div class="container"><div class="section-heading"><div>${eyebrow('How we approach a project')}<h2>Considered at every step.</h2></div><p>A shared understanding first.<br>A clear next step throughout.</p></div><div class="process-grid">${[['Discover','Listen to the challenge, explore the audience, and understand what matters.'],['Define','Set the direction, agree on priorities, and decide what success means.'],['Create','Bring the strategy to life through a consistent identity and experience.'],['Refine','Review, learn, and make thoughtful improvements as the work develops.']].map(([t,b],i)=>`<article><span class="index">0${i+1}</span><h3>${t}</h3><p>${b}</p></article>`).join('')}</div></div></section>${cta()}`
  },
  about: {
    title: 'About', description: 'The thinking behind Via Nova Marketing: strategic, modern, forward, trustworthy, and human.',
    content: `<section class="page-intro container">${eyebrow('About Via Nova')}<h1>A new path.<br>A higher way forward.</h1><p>Strategic in our thinking. Human in our approach.</p></section><section class="about-panel container"><div class="identity-panel">${logo()}<p>A HIGHER WAY FORWARD</p></div><div class="about-copy">${eyebrow('The idea that guides us')}<h2>Clarity for today.<br>Possibility for tomorrow.</h2><p>Based in Toronto and operated by EAST YORKER CORP., Via Nova Marketing brings together strategy, creativity, and a belief in purposeful progress. Our starting point is simple: understand the business before deciding what to create.</p><p>The upward path and guiding star in our identity represent direction and possibility. They remind us to keep the bigger picture in view while giving every step the attention it deserves.</p></div></section><section class="section container"><div class="section-heading"><div>${eyebrow('Our character')}<h2>What we bring to the work.</h2></div></div><div class="values-grid">${[['Strategic','Purpose-driven thinking. A clear reason behind each decision.'],['Modern','Fresh, relevant ideas with an eye on what comes next.'],['Forward','A focus on progress, with practical steps to get there.'],['Trustworthy','Honest communication and clarity about the work.'],['Human','People at the centre of the brand and the experience.'],['Motion-ready','An identity and approach built to move across formats.']].map(([t,b],i)=>`<article><span class="index">0${i+1}</span><h3>${t}</h3><p>${b}</p></article>`).join('')}</div></section><section class="landscape-banner"><div class="container"><p>People. Ideas. Strategy.</p><h2>A brighter tomorrow<br>starts with a clear direction.</h2></div></section>${cta()}`
  },
  work: {
    title: 'Work', description: 'The Via Nova Marketing portfolio is in development. Client case studies will be shared here.',
    content: `<section class="page-intro container">${eyebrow('Our work')}<h1>Behind every brand,<br>a story worth telling.</h1><p>Our portfolio is taking shape.</p></section><section class="work-content container"><div class="portfolio-placeholder"><div class="portfolio-heading"><span class="index">COMING SOON</span><span class="status-label">Case studies</span></div><h2>The challenge.<br>The thinking.<br>The way forward.</h2><p>This is where we’ll share our project stories, with context around the decisions and evidence behind the outcomes.</p><p class="disclosure">No client projects or results are presented in this initial portfolio.</p></div><div class="work-categories"><span>Brand strategy</span><span>Brand identity</span><span>Digital experiences</span><span>Content & campaigns</span></div></section>${cta()}`
  },
  contact: {
    title: 'Contact Our Toronto Marketing Agency', description: 'Call Via Nova Marketing at +1 (437) 237-6895 or email east_yorker@outlook.com. Based at 75 Thorncliffe Park Drive, Toronto, Ontario.',
    content: `<section class="page-intro container">${eyebrow('Let’s talk')}<h1>What does your<br>next chapter look like?</h1><p>Every new path starts with a first conversation.</p></section><section class="contact-grid container"><div class="contact-copy"><h2>Start with your ambition.<br>We’ll start with listening.</h2><p>Tell us about your business, the challenge in front of you, and where you’d like to go.</p><div class="contact-note"><h3>Get in touch</h3><p><a href="tel:+14372376895">+1 (437) 237-6895</a><br><a href="mailto:east_yorker@outlook.com">east_yorker@outlook.com</a></p><address>75 Thorncliffe Park Drive<br>Toronto, Ontario M4H 1L4<br>Canada</address><p>Call or email to start a conversation. You can also download a project brief below and attach it to your email.</p><p>This form does not send or store your information.</p></div><div class="contact-signoff"><span class="rule"></span><p>A Higher Way Forward</p></div></div><form id="brief-form"><h2 class="brief-heading">Prepare your project brief</h2><p class="brief-intro">Download a copy, then email it to us. This is not an online submission form.</p><div class="field-pair"><label>Your name<input name="name" autocomplete="name" required maxlength="120" placeholder="Your name"></label><label>Business <span>(optional)</span><input name="business" autocomplete="organization" maxlength="160" placeholder="Your business"></label></div><label>What would you like to explore?<select name="service" required><option value="">Select a service</option>${disciplines.map(s=>`<option>${s.title}</option>`).join('')}<option>I’m still exploring</option></select></label><label>What would you like to achieve?<textarea name="challenge" required rows="5" maxlength="5000" placeholder="Your goals, your audience, and the challenge you want to solve…"></textarea></label><label>Ideal timing <span>(optional)</span><input name="timing" maxlength="160" placeholder="When would you like to begin?"></label><button class="button" type="submit">Download project brief <span aria-hidden="true">↓</span></button><p id="form-status" class="form-status" role="status"></p><noscript><p>Enable JavaScript to download your brief. Nothing is submitted online.</p></noscript></form></section>`
  }
};
pages.privacy = {
  title: 'Website Privacy', description: 'How this website handles project briefs, contact links, and technical website data.',
  content: '<section class="page-intro container"><p class="eyebrow">Website information</p><h1>Privacy, in plain language.</h1><p>Last updated: September 16, 2026</p></section><section class="policy-copy container"><h2>Who operates this website</h2><p>Via Nova Marketing is operated by EAST YORKER CORP. Contact us at <a href="mailto:east_yorker@outlook.com">east_yorker@outlook.com</a> or +1 (437) 237-6895 about this website or your information.</p><h2>Your project brief</h2><p>The brief tool processes the details you enter in your browser and creates a text file for you to download. It does not submit those details to our server or save them in website storage. You choose whether to send the downloaded file to us.</p><h2>Calling or emailing us</h2><p>Phone and email links open your chosen phone or email application. If you contact us, we receive the information you choose to share so we can respond to your enquiry. Avoid sending passwords, payment details, or other sensitive information in a project brief.</p><h2>Hosting and website measurements</h2><p>Vercel hosts this website and may process technical request information to deliver and protect it. We use Vercel Web Analytics for aggregate measurements such as page views, referrers, device types, and approximate location. It does not use third-party cookies. Our integration removes query parameters from page URLs, excludes brief fields, and does not load when your browser sends Do Not Track. We do not install advertising pixels or Google Analytics cookies. Read <a href="https://vercel.com/docs/analytics/privacy-policy">Vercel’s analytics privacy information</a> for details.</p><h2>Your questions</h2><p>You can contact us to ask about information you have shared, request a correction, or discuss deletion. Our mailing address is 75 Thorncliffe Park Drive, Toronto, Ontario M4H 1L4, Canada.</p></section>'
};
export function layout(key, page) {
  const nav = [['services','Services'],['about','About'],['work','Work']].map(([slug,title])=>`<a href="${slug}.html" ${slug===key?'aria-current="page"':''}>${title}</a>`).join('');
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${page.title} — Via Nova Marketing</title><meta name="description" content="${page.description}"><meta name="theme-color" content="#0B2D45"><meta name="robots" content="index, follow"><link rel="canonical" href="https://vianovamarketing.ca/${key === 'index' ? '' : key + '.html'}"><meta property="og:title" content="${page.title} — Via Nova Marketing"><meta property="og:description" content="${page.description}"><meta property="og:type" content="website">${searchMetadata(key, page)}<link rel="icon" href="assets/monogram-adobe.png" type="image/png"><link rel="stylesheet" href="assets/fonts.css"><link rel="stylesheet" href="assets/styles.css"><script src="assets/site.js" defer></script><script src="assets/analytics.js" defer></script></head>
<body><a class="skip-link" href="#main">Skip to content</a><header class="site-header"><div class="container header-inner"><a class="brand" href="index.html" aria-label="Via Nova Marketing home">${logo()}</a><button class="menu-toggle" aria-expanded="false" aria-controls="main-nav" hidden>Menu <span aria-hidden="true">+</span></button><nav id="main-nav" aria-label="Main navigation">${nav}<a class="button nav-cta" href="contact.html" ${key==='contact'?'aria-current="page"':''}>Let’s talk ${arrow}</a></nav></div></header><main id="main">${page.content}</main><footer class="site-footer"><div class="container"><div class="footer-top"><a class="brand" href="index.html" aria-label="Via Nova Marketing home">${logo()}</a><p>Bolder brands.<br>Brighter tomorrows.</p><nav aria-label="Footer navigation"><a href="services.html">Services</a><a href="about.html">About</a><a href="work.html">Work</a><a href="contact.html">Contact</a><a href="privacy.html">Privacy</a></nav></div><div class="footer-contact"><a href="tel:+14372376895">+1 (437) 237-6895</a><a href="mailto:east_yorker@outlook.com">east_yorker@outlook.com</a><address>75 Thorncliffe Park Drive, Toronto, Ontario M4H 1L4, Canada</address><p>Via Nova Marketing is operated by EAST YORKER CORP.</p></div><div class="footer-bottom"><span>© ${new Date().getFullYear()} Via Nova Marketing</span><span>Strategy. Creativity. Real growth.</span></div></div></footer></body></html>`;
}
