const options = (name, values, type = 'radio') => `<div class="quote-options">${values.map(([value, label]) => `<label class="quote-option"><input type="${type}" name="${name}" value="${value}"><span>${label}</span></label>`).join('')}</div>`;
const field = (name, label, placeholder = '') => `<label>${label}<textarea name="${name}" ${name === 'Goals and audience' ? 'required' : ''} rows="3" maxlength="2000" placeholder="${placeholder}"></textarea></label>`;
export const quoteForm = `<section class="page-intro container"><p class="eyebrow">A higher way forward</p><h1>Let’s shape your next step.</h1><p>One service or a connected journey. Tell us what you have in mind, and we’ll use your brief to prepare a tailored response.</p></section>
<section class="container quote-layout"><aside class="quote-aside"><h2>Your vision.<br>A considered plan.</h2><p>You don’t need all the answers. Share what you know and we’ll help clarify the rest.</p><p>This is a quote request, not a booking. Scope, pricing and timing are agreed with you before work begins.</p><a href="contact.html">Prefer a quick enquiry?</a></aside>
<form id="quote-form" action="https://formspree.io/f/xqpaqedp" method="POST">
<div id="quote-progress" hidden><p id="quote-status" role="status"></p><progress max="6" value="1" aria-label="Project brief progress"></progress></div>
<fieldset data-step><legend tabindex="-1">1. Where are you now?</legend><p>Choose the closest fit.</p>${options('Business stage', [['Starting','Starting something new'],['Growing','Growing an existing business'],['Refreshing','Refreshing my brand or marketing'],['Guidance','I’m not sure — I need guidance']])}</fieldset>
<fieldset data-step><legend tabindex="-1">2. What would you like help with?</legend><p>Choose as many as you need. You can change these later.</p>${options('Services', [['Strategy','Strategy & positioning'],['Brand','Logo & brand identity'],['Website','Website & digital experience'],['Materials','Marketing materials'],['Content','Content & social media'],['Campaigns','Campaign planning'],['Full journey','The full journey'],['Guidance','Help me decide']], 'checkbox')}</fieldset>
<fieldset data-step><legend tabindex="-1">3. What are we building on?</legend><label>Business name (optional)<input name="Business" autocomplete="organization" maxlength="160"></label>${field('Existing assets','What do you already have? (optional)','For example: an idea, a logo, website, photos or social accounts. Starting from scratch is fine.')}<label>Website or social links (optional)<textarea name="Existing links" rows="2" maxlength="1500" placeholder="Paste any links you’d like us to review."></textarea></label></fieldset>
<fieldset data-step><legend tabindex="-1">4. What would you like to achieve?</legend>${field('Goals and audience','Tell us about your goals, audience and main challenge','What do you offer, who do you want to reach, and what would you like to improve? It’s okay to ask for guidance.')}
<div data-services="Strategy">${field('Strategy needs','Strategy: where would clarity help? (optional)','Your audience, positioning, competitors or marketing direction.')}</div>
<div data-services="Brand">${field('Brand needs','Brand: what needs creating or refreshing? (optional)','A name, logo, colours, brand voice or complete identity.')}</div>
<div data-services="Website">${field('Website needs','Website: what should visitors be able to do? (optional)','Learn about you, enquire, book, buy online, or something else.')}</div>
<div data-services="Materials">${field('Materials needed','Materials: which items do you need? (optional)','A brochure, presentation, menu, signage or other materials.')}</div>
<div data-services="Content">${field('Content needs','Content: where would you like support? (optional)','Planning, photos, video, social posts or ongoing support. Mention your channels.')}</div>
<div data-services="Campaigns">${field('Campaign needs','Campaigns: what are you promoting? (optional)','Your offer, audience, channels and any campaign dates.')}</div></fieldset>
<fieldset data-step><legend tabindex="-1">5. Budget and timing</legend><label>Budget direction<select name="Budget direction"><option>I need guidance</option><option>I have a budget in mind</option><option>I prefer to discuss this</option></select></label><label>Budget details (optional)<input name="Budget details" maxlength="200" placeholder="Amount, currency, and whether one-off or monthly"></label><label>When would you like to begin?<select name="Timing"><option>I’m exploring / not sure yet</option><option>As soon as practical</option><option>Within 1–3 months</option><option>Later / planning ahead</option><option>I have a specific date</option></select></label><label>Dates or timing details (optional)<input name="Timing details" maxlength="300" placeholder="Any launch date or important deadline"></label></fieldset>
<fieldset data-step><legend tabindex="-1">6. Review and send</legend><div id="quote-review" hidden></div><p>Use Back to change your answers. Name, email and a short description of your goals are required.</p><label>Your name<input name="name" autocomplete="name" required maxlength="120"></label><label>Your email<input type="email" name="email" autocomplete="email" required maxlength="254"></label><label>Phone (optional)<input type="tel" name="Phone" autocomplete="tel" maxlength="40"></label><p>By sending, you ask Via Nova to respond to your project request. Formspree processes your brief and may show a spam check. Please don’t include passwords or payment details. <a href="privacy.html">Privacy information</a>.</p><button class="button" id="quote-send" type="submit">Request a tailored quote <span aria-hidden="true">↗</span></button><p>After sending, you’ll see a confirmation page. If it fails, return here or email <a href="mailto:east_yorker@outlook.com">east_yorker@outlook.com</a>.</p></fieldset>
<div hidden><label>Leave empty<input name="_gotcha" tabindex="-1" autocomplete="off"></label></div><input type="hidden" name="_subject" value="Via Nova Marketing — tailored project request"><input type="hidden" name="message" id="quote-message">
<div class="quote-actions" hidden><button type="button" class="button outline" id="quote-back">Back</button><button type="button" class="button" id="quote-next">Continue <span aria-hidden="true">→</span></button></div><noscript><p>All sections are shown together. Complete the relevant questions and use Request a tailored quote to send.</p></noscript>
</form></section><script type="module" src="assets/quote.js"></script>`;
