import { questions } from '../public/assets/quote-questions.js';
const escape = text => String(text).replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;').replaceAll('>','&gt;');
const questionHtml = (q, index) => {
  const id = `question-${index}`;
  const controls = q.choices ? `<div class="quote-options">${q.choices.map(value => `<label class="quote-option"><input type="${q.multiple ? 'checkbox' : 'radio'}" name="${escape(q.id)}" value="${escape(value)}"><span>${escape(value)}</span></label>`).join('')}</div>` : `<label for="${id}">${q.required ? 'Your answer (required)' : 'Your answer (optional)'}</label>${q.type ? `<input id="${id}" type="${q.type}" name="${escape(q.id)}" ${q.required ? 'required' : ''} autocomplete="${q.autocomplete}" maxlength="${q.type === 'email' ? 254 : 160}">` : `<textarea id="${id}" name="${escape(q.id)}" ${q.required ? 'required' : ''} rows="3" maxlength="2000"></textarea>`}`;
  return `<fieldset data-question="${escape(q.id)}" aria-describedby="${id}-help"><legend tabindex="-1">${escape(q.title)}</legend><p id="${id}-help">${escape(q.help)}</p>${controls}<p data-error role="alert" hidden>Please choose an option, or select guidance.</p></fieldset>`;
};
export const quoteForm = `<section class="page-intro container"><p class="eyebrow">A higher way forward</p><h1>Let’s shape your next step.</h1><p>One service or a connected journey. Answer one relevant question at a time, then review your brief for a tailored response.</p></section>
<section class="container quote-layout"><aside class="quote-aside"><h2>Your vision.<br>A considered plan.</h2><p>You don’t need all the answers. Share what you know and we’ll help clarify the rest.</p><p>This is a quote request, not a booking. Scope, pricing and timing are agreed with you before work begins.</p><p><a href="contact.html">Prefer a quick enquiry or to contact Nabil?</a></p></aside>
<form id="quote-form" action="https://formspree.io/f/xqpaqedp" method="POST" hidden>
<div id="quote-progress"><p id="quote-status" role="status" aria-live="polite"></p><progress max="1" value="1" aria-label="Project brief progress"></progress></div>
<p id="quote-route-note" role="status" hidden></p>
${questions.map(questionHtml).join('')}
<fieldset id="quote-final" hidden><legend tabindex="-1">Here’s what we understood</legend><div id="quote-review"></div><p>This is your supplied brief, not verified research or an agreed scope. Use Edit to change an answer. Unanswered optional questions remain for discussion.</p><p>We review your brief, clarify what is feasible and agree scope, price and timing before work begins. We then create, review and deliver the agreed work, with ongoing support if arranged.</p><p>By sending, you ask Via Nova to respond to your project request. Formspree processes your brief and may show a spam check. Please don’t include passwords or payment details. <a href="privacy.html">Privacy information</a>.</p><button class="button" id="quote-send" type="submit">Request a tailored quote <span aria-hidden="true">↗</span></button><p>After sending, you’ll see a confirmation page. If it fails, return here or email <a href="mailto:east_yorker@outlook.com">east_yorker@outlook.com</a>.</p></fieldset>
<div hidden><label>Leave empty<input name="_gotcha" tabindex="-1" autocomplete="off"></label></div><input type="hidden" name="_subject" value="Via Nova Marketing — tailored project request"><input type="hidden" name="message" id="quote-message">
<div class="quote-actions"><button type="button" class="button outline" id="quote-back">Back</button><button type="button" class="button" id="quote-next">Continue <span aria-hidden="true">→</span></button></div><button type="button" class="small-link" id="quote-return" hidden>Return to summary</button><p>Optional questions can be left blank. Your answers stay on this page while you go back and make changes; refreshing or leaving the page clears them.</p>
</form><p id="quote-fallback">If the guided questions do not load, <a href="contact.html">send a quick enquiry</a> or <a href="mailto:east_yorker@outlook.com">email Nabil</a>.</p></section><script type="module" src="assets/quote.js"></script>`;
